# terraform/main.tf
# Root module — orchestrates all modules

# Create .simulated directory for local_file outputs
resource "local_file" "simulated_dir" {
  filename = "${path.module}/.simulated/.gitkeep"
  content  = "# Simulated cloud resources — generated by Terraform"
}

# ── Network Layer ─────────────────────────────────────────────
module "network" {
  source = "./modules/network"

  name_prefix          = local.name_prefix
  environment          = var.environment
  vpc_cidr             = var.vpc_cidr
  public_subnet_cidrs  = var.public_subnet_cidrs
  private_subnet_cidrs = var.private_subnet_cidrs
  availability_zones   = var.availability_zones
  tags                 = local.common_tags
}

# ── Security Layer ────────────────────────────────────────────
module "security" {
  source = "./modules/security"

  name_prefix = local.name_prefix
  environment = var.environment
  vpc_id      = module.network.vpc_id
  api_port    = var.api_port
  tags        = local.common_tags
}

# ── Compute Layer ─────────────────────────────────────────────
module "compute" {
  source = "./modules/compute"

  name_prefix        = local.name_prefix
  environment        = var.environment
  instance_count     = local.effective_instance_count
  instance_type      = local.current_env.instance_type
  private_subnet_ids = module.network.private_subnet_ids
  security_group_id  = module.security.security_group_id
  api_port           = var.api_port
  app_version        = var.app_version
  log_level          = local.current_env.log_level
  max_tasks          = var.max_tasks
  tags               = local.common_tags
}

# ── Configuration Summary ─────────────────────────────────────
# Generate a deployment summary file
resource "local_file" "deployment_summary" {
  filename = "${path.module}/.simulated/deployment-summary.json"
  content  = jsonencode({
    deployment = {
      timestamp   = timestamp()
      environment = var.environment
      project     = var.project_name
      version     = var.app_version
    }
    infrastructure = {
      vpc_id          = module.network.vpc_id
      instance_count  = local.effective_instance_count
      instance_type   = local.current_env.instance_type
      security_group  = module.security.security_group_id
      load_balancer   = module.compute.load_balancer_dns
      api_url         = module.compute.api_url
    }
    network = {
      vpc_cidr          = var.vpc_cidr
      public_subnets    = module.network.public_subnet_ids
      private_subnets   = module.network.private_subnet_ids
    }
    application = {
      log_level = local.current_env.log_level
      max_tasks = var.max_tasks
      port      = var.api_port
    }
  })

  depends_on = [module.network, module.security, module.compute]
}